### ISSUE TITLE
PD Milestones: Definition

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#26]
**Background**
PD is still unnecessary learning because trainees know they cannot fail it. This has been discussed many times and many solutions brought up, so this ticket is less about looking at everything we've done but focussing on new ideas to define PD milestones

**Acceptance criteria**

- [ ] Define 3 ways of measuring success of the PD curriculum
- [ ] Define what kind of automation is needed to track it

**Comment by kfklein15** [comment]
Suggestion of milestones:

1. Attendance: we track day attendance. Would it be possible to track only PD attendance (example of a WM5 trainee that didn't participate in PD exercise?)
2. Coursework: What percentage of coursework was done and passed?

None of the above suggestions prove that the trainee has learned the minimal skills to become employable. Some common ways of measuring these in the corporate world are:
- Interview competency-based questions
- 360 degrees evaluations
- Performance evaluation

Any input on this would be welcome.

**Comment by SallyMcGrath** [comment]
Hey you know we could actually use milestones. How has this not occurred to me before?

We could teach them how to use milestones and assign key tickets to milestones on their planner repo

They could need some percentage of tickets to be approved as Done by another person

**Comment by kfklein15** [comment]
Do you want to chat so we can map this idea in detail?

**Comment by kfklein15** [comment]
[Milestones Descriptions](https://docs.codeyourfuture.io/leaders/running-the-course/assessment/milestones)
[API Milestone](https://api.github.com/repos/CodeYourFuture/curriculum/milestones)

**Must have info in bold**
id	integer or string	yes	The ID or URL-encoded path of the project owned by the authenticated user
**title	string	yes	The title of a milestone**
description	string	no	The description of the milestone
**due_date	string	no	The due date of the milestone (YYYY-MM-DD)**
start_date	string	no	The start date of the milestone (YYYY-MM-DD)

**Steps for the first pilot**
- [ ] Create my own coursework board
- [ ] Batch clone 1 module (use Kamino)
- [ ] Assign milestones (check SIFA) with Level 1, Level 2, Level 3 and Dealbreaker to Key and Mandatory work only
- [ ] Make notes of any constraints/issues in the process
- [ ] Review with Sally/Lara

Count of roughly a number of coursework per Level and per timeframe
